<a href="https://colab.research.google.com/github/ridvanyigit/py-data-analysis-crash-codes/blob/main/NumPy_Crash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [157]:
import pandas as pd
import numpy as np

In [158]:
list1 = [0,1,2,3,4]

In [159]:
arr_1D= np.array(list1)
arr_1D

array([0, 1, 2, 3, 4])

In [160]:
list1.append(5)
list1

[0, 1, 2, 3, 4, 5]

In [161]:
arr_1D + 3

array([3, 4, 5, 6, 7])

In [162]:
list2 = [[0,1,2],[3,4,5],[6,7,8]]

In [163]:
arr_2D = np.array(list2)
arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
arr_2D = np.array(list2, dtype='float')
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [165]:
arr_2D.astype('str')

array([['0.0', '1.0', '2.0'],
       ['3.0', '4.0', '5.0'],
       ['6.0', '7.0', '8.0']], dtype='<U32')

In [166]:
arr_2D.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [167]:
list1.append('6')

In [168]:
np2list = arr_2D.tolist()
np2list

[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]

In [169]:
arr_2D.tostring()

<ipython-input-169-4798ef000470>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  arr_2D.tostring()


b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @'

In [170]:
arr_2D.tobytes()

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @'

## dtype & shape

In [171]:
list2

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [172]:
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [173]:
arr_1D

array([0, 1, 2, 3, 4])

In [174]:
arr_2D.astype('float')

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [175]:
print('Shape:', arr_2D.shape)

Shape: (3, 3)


In [176]:
arr_2D.dtype

dtype('float64')

In [177]:
arr_2D.size

9

In [178]:
arr_1D.size

5

In [179]:
arr_2D.ndim

2

In [180]:
arr_1D.ndim

1

In [181]:
arr_1D = arr_1D + 4
arr_1D

array([4, 5, 6, 7, 8])

In [182]:
arr_1D[0]

4

In [183]:
arr_2D[1]

array([3., 4., 5.])

In [184]:
arr_2D[1][0]

3.0

In [185]:
boolar = arr_2D < 5
boolar

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [186]:
arr_2D[boolar]

array([0., 1., 2., 3., 4.])

In [187]:
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [188]:
arr_2D[::-1]

array([[6., 7., 8.],
       [3., 4., 5.],
       [0., 1., 2.]])

In [189]:
arr_2D[::-1, ::-1]

array([[8., 7., 6.],
       [5., 4., 3.],
       [2., 1., 0.]])

## np.nan & np.inf

In [190]:
np.nan

nan

In [191]:
np.inf

inf

In [192]:
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [193]:
arr_2D[0][0] = np.nan
arr_2D[0][1] = np.inf
arr_2D

array([[nan, inf,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [194]:
np.isnan(arr_2D)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [195]:
np.isinf(arr_2D)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [196]:
missing_flag = np.isnan(arr_2D) | np.isinf(arr_2D)
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [197]:
# Replace 'np.inf' and 'np.nan' with '0'
arr_2D[missing_flag]

array([nan, inf])

In [198]:
arr_2D[missing_flag] = 0
arr_2D

array([[0., 0., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Statistical Operation

*   mean
*   std
*   var

In [199]:
arr_2D.mean()

3.888888888888889

In [200]:
arr_2D.std()

2.7261875880856214

In [201]:
arr_2D.var()

7.432098765432098

In [202]:
arr_2D.min()

0.0

In [203]:
arr_2D.max()

8.0

In [204]:
arr_2D.squeeze()

array([[0., 0., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [205]:
arr_2D.cumsum()

array([ 0.,  0.,  2.,  5.,  9., 14., 20., 27., 35.])

In [206]:
arr = arr_2D[:2, :2]
arr

array([[0., 0.],
       [3., 4.]])

In [207]:
arr_2D[1:3, 1:3]

array([[4., 5.],
       [7., 8.]])

In [208]:
arr_2D.reshape(1,9)

array([[0., 0., 2., 3., 4., 5., 6., 7., 8.]])

In [209]:
arr_2D.reshape(9,1)

array([[0.],
       [0.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.]])

In [211]:
a = arr_2D.reshape(1,9)
a

array([[0., 0., 2., 3., 4., 5., 6., 7., 8.]])

In [212]:
a.ndim

2

In [220]:
b = arr_2D.flatten()
b #copy

array([0., 0., 2., 3., 4., 5., 6., 7., 8.])

In [215]:
b.ndim

1

In [221]:
c = arr_2D.ravel()
c #reference

array([0., 0., 2., 3., 4., 5., 6., 7., 8.])

In [219]:
c.ndim

1

## sequence, repetitions, and random numbers

In [222]:
np.arange(1,5, dtype='int')

array([1, 2, 3, 4])

In [225]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [241]:
np.linspace(1,50,21)

array([ 1.  ,  3.45,  5.9 ,  8.35, 10.8 , 13.25, 15.7 , 18.15, 20.6 ,
       23.05, 25.5 , 27.95, 30.4 , 32.85, 35.3 , 37.75, 40.2 , 42.65,
       45.1 , 47.55, 50.  ])

In [242]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [249]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [250]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [251]:
a = [1,2,3]
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [254]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [257]:
np.random.rand(4,3)

array([[0.86461376, 0.84737709, 0.5731551 ],
       [0.574907  , 0.04511905, 0.70829754],
       [0.32697687, 0.49861456, 0.92308223],
       [0.66626923, 0.59293964, 0.75667099]])

In [258]:
np.random.randn(4,3)

array([[-1.31411375,  1.30997002,  0.35542102],
       [ 0.73515413,  1.02298683, -0.54763522],
       [ 0.6598365 ,  1.21647857, -0.52174735],
       [-0.46448607, -0.21697789, -0.53785613]])

In [261]:
np.random.randint(0,10)

9

In [262]:
np.random.randint(0,10, [4,3])

array([[8, 1, 6],
       [5, 2, 0],
       [0, 5, 3],
       [4, 9, 3]])

In [266]:
np.random.seed(0) # no random
np.random.randint(0,10, [4,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [267]:
np.unique(arr_2D)

array([0., 2., 3., 4., 5., 6., 7., 8.])

In [269]:
uniqes, counts = np.unique(arr_2D, return_counts=True)
print(uniqes)
print(counts)

[0. 2. 3. 4. 5. 6. 7. 8.]
[2 1 1 1 1 1 1 1]
