<a href="https://colab.research.google.com/github/ridvanyigit/py-data-analysis-crash-codes/blob/main/NumPy_Crash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **P A R T - 1**

In [1]:
import pandas as pd
import numpy as np

In [2]:
list1 = [0,1,2,3,4]

In [3]:
arr_1D= np.array(list1)
arr_1D

array([0, 1, 2, 3, 4])

In [4]:
list1.append(5)
list1

[0, 1, 2, 3, 4, 5]

In [5]:
arr_1D + 3

array([3, 4, 5, 6, 7])

In [6]:
list2 = [[0,1,2],[3,4,5],[6,7,8]]

In [7]:
arr_2D = np.array(list2)
arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr_2D = np.array(list2, dtype='float')
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [9]:
arr_2D.astype('str')

array([['0.0', '1.0', '2.0'],
       ['3.0', '4.0', '5.0'],
       ['6.0', '7.0', '8.0']], dtype='<U32')

In [10]:
arr_2D.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
list1.append('6')

In [12]:
np2list = arr_2D.tolist()
np2list

[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]

In [13]:
arr_2D.tostring()

<ipython-input-13-4798ef000470>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  arr_2D.tostring()


b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @'

In [14]:
arr_2D.tobytes()

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @'

## dtype & shape

In [15]:
list2

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [16]:
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [17]:
arr_1D

array([0, 1, 2, 3, 4])

In [18]:
arr_2D.astype('float')

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [19]:
print('Shape:', arr_2D.shape)

Shape: (3, 3)


In [20]:
arr_2D.dtype

dtype('float64')

In [21]:
arr_2D.size

9

In [22]:
arr_1D.size

5

In [23]:
arr_2D.ndim

2

In [24]:
arr_1D.ndim

1

In [25]:
arr_1D = arr_1D + 4
arr_1D

array([4, 5, 6, 7, 8])

In [26]:
arr_1D[0]

4

In [27]:
arr_2D[1]

array([3., 4., 5.])

In [28]:
arr_2D[1][0]

3.0

In [29]:
boolar = arr_2D < 5
boolar

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [30]:
arr_2D[boolar]

array([0., 1., 2., 3., 4.])

In [31]:
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [32]:
arr_2D[::-1]

array([[6., 7., 8.],
       [3., 4., 5.],
       [0., 1., 2.]])

In [33]:
arr_2D[::-1, ::-1]

array([[8., 7., 6.],
       [5., 4., 3.],
       [2., 1., 0.]])

## np.nan & np.inf

In [34]:
np.nan

nan

In [35]:
np.inf

inf

In [36]:
arr_2D

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [37]:
arr_2D[0][0] = np.nan
arr_2D[0][1] = np.inf
arr_2D

array([[nan, inf,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [38]:
np.isnan(arr_2D)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [39]:
np.isinf(arr_2D)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [40]:
missing_flag = np.isnan(arr_2D) | np.isinf(arr_2D)
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [41]:
# Replace 'np.inf' and 'np.nan' with '0'
arr_2D[missing_flag]

array([nan, inf])

In [42]:
arr_2D[missing_flag] = 0
arr_2D

array([[0., 0., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Statistical Operation

*   mean
*   std
*   var

In [43]:
arr_2D.mean()

3.888888888888889

In [44]:
arr_2D.std()

2.7261875880856214

In [45]:
arr_2D.var()

7.432098765432098

In [46]:
arr_2D.min()

0.0

In [47]:
arr_2D.max()

8.0

In [48]:
arr_2D.squeeze()

array([[0., 0., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [49]:
arr_2D.cumsum()

array([ 0.,  0.,  2.,  5.,  9., 14., 20., 27., 35.])

In [50]:
arr = arr_2D[:2, :2]
arr

array([[0., 0.],
       [3., 4.]])

In [51]:
arr_2D[1:3, 1:3]

array([[4., 5.],
       [7., 8.]])

In [52]:
arr_2D.reshape(1,9)

array([[0., 0., 2., 3., 4., 5., 6., 7., 8.]])

In [53]:
arr_2D.reshape(9,1)

array([[0.],
       [0.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.]])

In [54]:
a = arr_2D.reshape(1,9)
a

array([[0., 0., 2., 3., 4., 5., 6., 7., 8.]])

In [55]:
a.ndim

2

In [56]:
b = arr_2D.flatten()
b #copy

array([0., 0., 2., 3., 4., 5., 6., 7., 8.])

In [57]:
b.ndim

1

In [58]:
c = arr_2D.ravel()
c #reference

array([0., 0., 2., 3., 4., 5., 6., 7., 8.])

In [59]:
c.ndim

1

## sequence, repetitions, and random numbers

In [60]:
np.arange(1,5, dtype='int')

array([1, 2, 3, 4])

In [61]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [62]:
np.linspace(1,50,21)

array([ 1.  ,  3.45,  5.9 ,  8.35, 10.8 , 13.25, 15.7 , 18.15, 20.6 ,
       23.05, 25.5 , 27.95, 30.4 , 32.85, 35.3 , 37.75, 40.2 , 42.65,
       45.1 , 47.55, 50.  ])

In [63]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [64]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
a = [1,2,3]
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [67]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [68]:
np.random.rand(4,3)

array([[0.78359722, 0.35026419, 0.28272636],
       [0.19169173, 0.07461594, 0.0428259 ],
       [0.5777998 , 0.16350757, 0.266823  ],
       [0.7941063 , 0.09348692, 0.3232317 ]])

In [69]:
np.random.randn(4,3)

array([[ 0.18036375, -0.07465468,  0.37447767],
       [-0.72802177, -0.86470688, -0.33077569],
       [ 0.49441194, -1.0173792 ,  1.01227581],
       [-0.36837905, -0.53192593,  0.49692607]])

In [70]:
np.random.randint(0,10)

9

In [71]:
np.random.randint(0,10, [4,3])

array([[9, 4, 7],
       [7, 0, 8],
       [5, 7, 3],
       [4, 5, 3]])

In [72]:
np.random.seed(0) # no random
np.random.randint(0,10, [4,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [73]:
np.unique(arr_2D)

array([0., 2., 3., 4., 5., 6., 7., 8.])

In [74]:
uniqes, counts = np.unique(arr_2D, return_counts=True)
print(uniqes)
print(counts)

[0. 2. 3. 4. 5. 6. 7. 8.]
[2 1 1 1 1 1 1 1]


# **P   A   R   T   -   2**

In [76]:
arr = np.array([8, 94, 8, 56, 1, 3, 4, 5, 7])
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [77]:
index_gt10 = np.where(arr > 10)
index_gt10

(array([1, 3]),)

In [81]:
arr[index_gt10]

array([94, 56])

In [82]:
arr[arr>10]

array([94, 56])

In [83]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [84]:
np.where(arr>10, 'gt10', 'lt10')

array(['lt10', 'gt10', 'lt10', 'gt10', 'lt10', 'lt10', 'lt10', 'lt10',
       'lt10'], dtype='<U4')

In [85]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [86]:
arr.max()

94

In [87]:
arr.argmax()

1

In [92]:
arr.argmin() #it returns index

4

In [93]:
arr[arr.argmin()] #it returns value

1

## Read and Write CSV File

*   np.genfromtxt() --> multiple data
*   np.loadtxt() --> text data

In [101]:
# https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv

In [107]:
data = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',
              skip_header= 1,
              filling_values=-1000,
              dtype='float',
              delimiter=',')

In [108]:
data.shape

(392, 9)

In [109]:
data[:3]

array([[ 1.800e+01,  8.000e+00,  3.070e+02,  1.300e+02,  3.504e+03,
         1.200e+01,  7.000e+01,  1.000e+00, -1.000e+03],
       [ 1.500e+01,  8.000e+00,  3.500e+02,  1.650e+02,  3.693e+03,
         1.150e+01,  7.000e+01,  1.000e+00, -1.000e+03],
       [ 1.800e+01,  8.000e+00,  3.180e+02,  1.500e+02,  3.436e+03,
         1.100e+01,  7.000e+01,  1.000e+00, -1.000e+03]])

In [110]:
np.set_printoptions(suppress=True)
data[:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [121]:
data2 = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',
              skip_header= 1,
              dtype= None,
              delimiter=',')

<ipython-input-121-9306164c99de>:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data2 = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',


In [122]:
data2[:3]

array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [127]:
np.savetxt('data.csv', data, delimiter=',') # Save the NumPy array 'data' to a CSV file named 'data.csv'.
                                           # The 'delimiter' argument specifies that commas should be used
                                           # to separate values in the file. This file can be opened with
                                           # text editors or spreadsheet programs.

In [128]:
data

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [126]:
np.save('data.npy', data) # save the array in NumPy's .npy format,
                           # which is a binary format for storing NumPy arrays efficiently.
                           # This file can be loaded using np.load()

In [129]:
np.savez('data2.npz', data, data2) # Save multiple arrays into a single .npz file.
                                   # In this case, it saves 'data' and 'data2' arrays.
                                   # This compressed file can be loaded using np.load().

In [130]:
d = np.load('data.npy')
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [131]:
d2 = np.load('data2.npz')
d2

NpzFile 'data2.npz' with keys: arr_0, arr_1

In [132]:
d2.files

['arr_0', 'arr_1']

In [135]:
d2['arr_0']

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [138]:
d2['arr_1']

array([(18. , 8, 307. , 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15. , 8, 350. , 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18. , 8, 318. , 150, 3436, 11. , 70, 1, b'"plymouth satellite"'),
       (16. , 8, 304. , 150, 3433, 12. , 70, 1, b'"amc rebel sst"'),
       (17. , 8, 302. , 140, 3449, 10.5, 70, 1, b'"ford torino"'),
       (15. , 8, 429. , 198, 4341, 10. , 70, 1, b'"ford galaxie 500"'),
       (14. , 8, 454. , 220, 4354,  9. , 70, 1, b'"chevrolet impala"'),
       (14. , 8, 440. , 215, 4312,  8.5, 70, 1, b'"plymouth fury iii"'),
       (14. , 8, 455. , 225, 4425, 10. , 70, 1, b'"pontiac catalina"'),
       (15. , 8, 390. , 190, 3850,  8.5, 70, 1, b'"amc ambassador dpl"'),
       (15. , 8, 383. , 170, 3563, 10. , 70, 1, b'"dodge challenger se"'),
       (14. , 8, 340. , 160, 3609,  8. , 70, 1, b'"plymouth \'cuda 340"'),
       (15. , 8, 400. , 150, 3761,  9.5, 70, 1, b'"chevrolet monte carlo"'),
       (14. , 8, 455. , 225, 3086, 10. , 70, 1

## Concat with Row and Col wise

In [139]:
arr1 = np.zeros([4,4])
arr2 = np.ones([4,4])

In [140]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

> Cocatenate

In [145]:
# Joins two or more arrays along a specified axis.
np.concatenate([arr1, arr2], axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

> Vstack

In [147]:
# Vertically stacks two arrays on top of each other.
np.vstack([arr1, arr2])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

> np.r

In [148]:
# Provides a shortcut (index trick) to concatenate two arrays vertically.
np.r_[arr1, arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [149]:
np.concatenate([arr1, arr2], axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

> hstack

In [152]:
# Horizontally stacks two arrays side-by-side.
np.hstack([arr1, arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

> np.c_

In [153]:
# Provides a shortcut (index trick) to horizontally stack arrays.
np.c_[arr1, arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

## Sort a NumPy Array

In [155]:
arr = np.random.randint(1, 10, size= [10,5])
arr

array([[3, 1, 4, 6, 5],
       [5, 7, 5, 5, 4],
       [5, 5, 9, 5, 4],
       [8, 6, 6, 1, 2],
       [6, 4, 1, 6, 1],
       [2, 3, 5, 3, 1],
       [4, 3, 1, 8, 6],
       [1, 3, 8, 3, 3],
       [4, 4, 3, 4, 5],
       [2, 3, 2, 5, 7]])

In [160]:
np.sort(arr, axis=0)

array([[1, 1, 1, 1, 1],
       [2, 3, 1, 3, 1],
       [2, 3, 2, 3, 2],
       [3, 3, 3, 4, 3],
       [4, 3, 4, 5, 4],
       [4, 4, 5, 5, 4],
       [5, 4, 5, 5, 5],
       [5, 5, 6, 6, 5],
       [6, 6, 8, 6, 6],
       [8, 7, 9, 8, 7]])

In [161]:
np.sort(arr, axis=1)

array([[1, 3, 4, 5, 6],
       [4, 5, 5, 5, 7],
       [4, 5, 5, 5, 9],
       [1, 2, 6, 6, 8],
       [1, 1, 4, 6, 6],
       [1, 2, 3, 3, 5],
       [1, 3, 4, 6, 8],
       [1, 3, 3, 3, 8],
       [3, 4, 4, 4, 5],
       [2, 2, 3, 5, 7]])

In [162]:
sorted_index = arr[:, 0].argsort()
sorted_index

array([7, 5, 9, 0, 6, 8, 1, 2, 4, 3])

In [163]:
arr[sorted_index]

array([[1, 3, 8, 3, 3],
       [2, 3, 5, 3, 1],
       [2, 3, 2, 5, 7],
       [3, 1, 4, 6, 5],
       [4, 3, 1, 8, 6],
       [4, 4, 3, 4, 5],
       [5, 7, 5, 5, 4],
       [5, 5, 9, 5, 4],
       [6, 4, 1, 6, 1],
       [8, 6, 6, 1, 2]])

## Working with Dates

In [164]:
d = np.datetime64('2023-05-01 23:10:00')
d

numpy.datetime64('2023-05-01T23:10:00')

In [173]:
oneday = np.timedelta64(1, 'D')
oneday

numpy.timedelta64(1,'D')

In [174]:
oneminute = np.timedelta64(1, 'm')
oneminute

numpy.timedelta64(1,'m')

In [172]:
print('d + 10 :', d + 10,'\n')
print('d - 10 :', d - 10,'\n')
print('d + 10 days :', d + 10 * np.timedelta64(1, 'D'),'\n')

d + 10 : 2023-05-01T23:10:10 

d - 10 : 2023-05-01T23:09:50 

d + 10 days : 2023-05-11T23:10:00 



In [179]:
dates = np.arange(np.datetime64('2023-05-01'), np.datetime64('2023-05-10'))
dates

array(['2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04',
       '2023-05-05', '2023-05-06', '2023-05-07', '2023-05-08',
       '2023-05-09'], dtype='datetime64[D]')

## NumPy Advanced Function

> vectorize

In [180]:
def foo(x):
  if x % 2 == 1:
    return x**2
  else:
    return x/2

foo(11)

121

In [182]:
foo_v = np.vectorize(foo, otypes=[float])

In [183]:
arr

array([[3, 1, 4, 6, 5],
       [5, 7, 5, 5, 4],
       [5, 5, 9, 5, 4],
       [8, 6, 6, 1, 2],
       [6, 4, 1, 6, 1],
       [2, 3, 5, 3, 1],
       [4, 3, 1, 8, 6],
       [1, 3, 8, 3, 3],
       [4, 4, 3, 4, 5],
       [2, 3, 2, 5, 7]])

In [184]:
foo_v(arr)

array([[ 9.,  1.,  2.,  3., 25.],
       [25., 49., 25., 25.,  2.],
       [25., 25., 81., 25.,  2.],
       [ 4.,  3.,  3.,  1.,  1.],
       [ 3.,  2.,  1.,  3.,  1.],
       [ 1.,  9., 25.,  9.,  1.],
       [ 2.,  9.,  1.,  4.,  3.],
       [ 1.,  9.,  4.,  9.,  9.],
       [ 2.,  2.,  9.,  2., 25.],
       [ 1.,  9.,  1., 25., 49.]])